# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Purchasing Power Procurement Blog
tagline:             <br/>&nbsp;&nbsp;&nbsp;Enabling Purchasing Power for Professional Buyers
description:         Blog about procurement templates and tools for procurement managers to enable purchasing power. 
url:                 http://blog.purchasingtoolpak.com
baseurl:             
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              David Mak
  url:               https://purchasingtoolpak.com
  email:             https://purchasingtoolpak.com/#contact

# Custom vars
version:             1.0.0

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
   
# Google services
#  google_analytics: UA-86996516-1
