# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Purchasing Toolpak Blog
tagline:             'Tools and Templates for Professional Buyers'
description:         'Click here to return to <a href="http://purchasingtoolpak.com" target="_blank">Purchasing Toolpak</a> a site focused on tools and templates for professional buyers.</a>.'
url:                 http://blog.purchasingtoolpak.com
baseurl:             
paginate:            5

# About/contact
author:
  name:              David Mak
  url:               https://purchasingtoolpak.com
  email:             https://purchasingtoolpak.com/#contact

# Custom vars
version:             1.0.0

#gems:
# - jekyll-sitemap
  
# Google services
#  google_analytics: UA-86996516-1
