# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Procurement Blog by Purchasing Toolpak
tagline:             Procurement Tools and Templates by Purchasing Toolpak LLC
description:         Pocurement blog focused on news and information about tools and templates for procurement professionals.
url:                 http://blog.purchasingtoolpak.com
baseurl:             
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              David Mak
  url:               https://purchasingtoolpak.com
  email:             https://purchasingtoolpak.com/#contact

# Custom vars
version:             1.0.0

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll/minibundle
  
# Google services
#  google_analytics: UA-86996516-1

# minifier settings
minibundle:
  minifier_commands:
    js: uglifyjs -
